### PR TITLE
(maint) Fixing the github action

### PR DESCRIPTION
**Pull request by gregohardy**

### CODE REVIEW

**Review by RandomNoun7 — APPROVED** [review]

**Review by RandomNoun7 — APPROVED** [review]

**Review by dBotLFG — COMMENTED** [review]
Why is this referencing an external repo?

**Comment by RandomNoun7** [comment]
@dBotLFG Most github actions are powered by external repo's. The `puppetlabs/action-litmus_spec@master` is an external repo that we use to centralize the administration of how we do spec testing for puppet modules. The reference in this PR is changed to my personal fork because the fix on my forks branch has not yet been merged into the upstream puppetlabs repo. When the fix is merged into the upstream repo, this change can be reverted, but until then this fix gets us up and running.

**Comment by dBotLFG** [comment]
so, emergency fix. Is there a ticket to track the real fix and subsequently revert this when fix is merged into the upstream labs repo?  Apologies for the pedantry, I get nervous when personal repos are tied in.

**Comment by RandomNoun7** [comment]
Yup, emergency fix, and I'm creating the tracking ticket now to ensure we circle back to this, and multiple of us are going to get notifications when the upstream repo merges the fix. I can't promise it will be soon, but we'll make sure to revert this when we can.

**Comment by dBotLFG** [comment]
Cool beans, thank you!

**Pull request merged**
